# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-symlinks

-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.2.1
    hooks:
    - id: shellcheck
      args: [-x]

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.7
    hooks:
    - id: autopep8
      args: ["-i", "--ignore=E402", "--max-line-length=150"]

-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      args: ["--max-line-length=150"]
