#!/usr/bin/env bash

hub_addr=10
send_interval=0.01

if ! i2cdetect -y 1 | grep -q "${hub_addr} "; then
  echo "This is not an old pi-top [4] device - exiting..."
  exit 0
fi

echo "* Stopping device manager so that firmware is upgraded properly"
sudo systemctl stop pt-device-manager

echo "* Upgrading firmware"
if sudo /usr/lib/pt-firmware-updater/pt-firmware-updater "0x${hub_addr}" "${send_interval}"; then
	echo "Reboot required - press ENTER..."
	read -r REPLY <&1

	sudo shutdown -h now
fi
