#!/usr/bin/env bash

if sudo i2cdetect -y 1 | grep 11; then
  echo "Firmware already upgraded"
  exit 0
fi

echo "To update the hub you will need to shutdown after installing the firmware. On next boot your pt[4] hub will use the i2c address 0x11. You may need to download the latest pi-topOS."

echo "Do you wish to continue? [Yy|Nn] "

read -r REPLY <&1

if [[ $REPLY =~ ^[Nn]$ ]]; then
  exit 1
fi

/usr/lib/pt-firmware-updater/src/FwUpdater

sudo systemctl enable pt-sys-oled.service

sudo shutdown -h now
