#!/usr/bin/python3

from hub_communicator import HubCommunicator

# def verifyFwUpdateSuccess(self): #TODO last
#     versionOnHardware = self.getFwVersion()
#     versionFromFile = readfile
#     "last_confirmed_fw_ver"
#     if (versionOnHardware > versionFromFile):
#         update
#         file
#         return verifySuccess
#     return error

hub = HubCommunicator("/usr/lib/pt-firmware-updater/bin/hub_I2C_0x11.bin")

hub.update_firmware()
