#!/usr/bin/python3

from hub_communicator import HubCommunicator
from sys import argv, exit

if len(argv) < 2:
    # TODO: automatically get from host information
    print("I2C address required")
    exit(1)

i2c_addr = argv[1]
if len(argv) > 2:
    send_packet_interval_str = argv[2]
    try:
        send_packet_interval = float(send_packet_interval_str)
    except Exception as e:
        print("Invalid value for packet interval")
        exit(1)
else:
    send_packet_interval = 0.2


hub = HubCommunicator(int(
    i2c_addr, 16), "/usr/lib/pt-firmware-updater/bin/hub_I2C_0x11.bin", send_packet_interval)

hub.update_firmware()
